CREATE TABLE USERS (
	Id VARCHAR(200) NOT NULL auto_increment PRIMARY KEY,
	FName VARCHAR(20) NOT NULL,
	LName VARCHAR(20) NOT NULL,
	Gender CHAR(1) NOT NULL,
	Email VARCHAR(40) NOT NULL,
	Phone VARCHAR(20),
	Password VARCHAR(100) NOT NULL
);
